# .pre-commit-config.yaml
repos:
  # compilerla/conventional-pre-commit 훅을 제거하고,
  # commitlint CLI를 직접 실행하는 훅을 추가합니다.
  - repo: local
    hooks:
      - id: commitlint
        name: Commitlint
        entry: /Users/yjin/Documents/code/Shifterz/node_modules/.bin/commitlint --edit

        language: system # 시스템에 설치된 Node.js와 commitlint를 사용
        stages: [commit-msg]
        # commitlint가 올바르게 실행되려면 Node.js와 commitlint 패키지가 전역 또는 프로젝트에 설치되어 있어야 합니다.
        # (npm install -g @commitlint/cli 또는 프로젝트 devDependencies에 설치)

  # (선택 사항) 기타 유용한 pre-commit 훅들 (이 부분은 그대로 유지합니다.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
