/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        /* ------------------------------------------------------ */
        /* --- primitive color --- */
        /* ------------------------------------------------------ */
        'alpha-black0': '#00000000',
        'alpha-black10': '#0000001a',
        'alpha-black25': '#00000040',
        'alpha-black50': '#00000080',
        'alpha-black75': '#000000bf',

        'alpha-white0': '#ffffff00',
        'alpha-white10': '#ffffff1a',
        'alpha-white25': '#ffffff40',
        'alpha-white50': '#ffffff80',
        'alpha-white75': '#ffffffbf',

        'danger-5': '#fdefec',
        'danger-10': '#fcdfd9',
        'danger-20': '#f7afa1',
        'danger-30': '#f48771',
        'danger-40': '#f05f42',
        'danger-50': '#de3412',
        'danger-60': '#bd2c0f',
        'danger-70': '#8a240f',
        'danger-80': '#5c180a',
        'danger-90': '#390d05',
        'danger-95': '#260903',

        'gray-0': '#ffffff',
        'gray-10': '#e6e8ea',

        'gray-5': '#f4f5f6',
        'gray-20': '#cdd1d5',
        'gray-30': '#b1b8be',
        'gray-40': '#8a949e',
        'gray-50': '#6d7882',
        'gray-60': '#58616a',
        'gray-70': '#464c53',
        'gray-80': '#33363d',
        'gray-90': '#1e2124',
        'gray-95': '#131416',
        'gray-100': '#000000',

        'information-5': '#e7f4fe',
        'information-10': '#d3ebfd',
        'information-20': '#9ed2fa',
        'information-30': '#5fb5f7',
        'information-40': '#2098f3',
        'information-50': '#0b78cb',
        'information-60': '#096ab3',
        'information-70': '#085691',
        'information-80': '#053961',
        'information-90': '#03253f',
        'information-95': '#021a2c',

        'point-5': '#fdfcec',
        'point-10': '#faf6c7',
        'point-20': '#f6efa2',
        'point-30': '#f3e97c',
        'point-40': '#eee147',
        'point-50': '#e0cf15',
        'point-60': '#bbad11',
        'point-70': '#958a0e',
        'point-80': '#70680a',
        'point-90': '#4b4507',
        'point-95': '#252303',
        'point-100': '#131102',

        'primary-5': '#eefbfc',
        'primary-10': '#dcf6f9',
        'primary-20': '#b9edf3',
        'primary-30': '#96e5ed',
        'primary-40': '#73dce7',
        'primary-50': '#51d3e1',
        'primary-60': '#2ecadc',
        'primary-70': '#1b909d',
        'primary-80': '#15707a',
        'primary-90': '#0f5057',
        'primary-95': '#062023',

        'success-5': '#eaf6ec',
        'success-10': '#d8eedd',
        'success-20': '#a9dab4',
        'success-30': '#7ec88e',
        'success-40': '#3fa654',
        'success-50': '#228738',
        'success-60': '#267337',
        'success-70': '#285d33',
        'success-80': '#1f4727',
        'success-90': '#122b18',
        'success-95': '#0e2012',

        'warning-5': '#fff3db',
        'warning-10': '#ffe0a3',
        'warning-20': '#ffc95c',
        'warning-30': '#ffb114',
        'warning-40': '#c78500',
        'warning-50': '#9e6a00',
        'warning-60': '#8a5c00',
        'warning-70': '#614100',
        'warning-80': '#422c00',
        'warning-90': '#2e1f00',
        'warning-95': '#241800',

        /* ------------------------------------------------------ */
        /* --- light mode color --- */
        /* ------------------------------------------------------ */
        'action-disabled': '#cdd1d5',
        'action-primary': '#2ecadc',
        'action-primary-active': '#1b909d',
        'action-primary-pressed': '#dcf6f9',
        'action-primary-selected': '#eefbfc',
        'action-white': '#ffffff',

        'alpha-base0': '#ffffff00',
        'alpha-base10': '#ffffff1a',
        'alpha-base25': '#ffffff40',
        'alpha-base50': '#ffffff80',
        'alpha-base75': '#ffffffbf',
        'alpha-base100': '#ffffff',

        'alpha-inverse0': '#00000000',
        'alpha-inverse10': '#0000001a',
        'alpha-inverse25': '#00000040',
        'alpha-inverse50': '#00000080',
        'alpha-inverse75': '#000000bf',
        'alpha-inverse100': '#000000',

        'alpha-shadow1': '#0000000d',
        'alpha-shadow2': '#00000014',
        'alpha-shadow3': '#0000001f',

        'background-black': '#000000',
        'background-dim': '#000000bf',
        'background-gray-subtle1': '#f4f5f6',
        'background-gray-subtle2': '#e6e8ea',
        'background-inverse': '#1e2124',
        'background-white': '#ffffff',

        'border-danger': '#de3412',
        'border-danger-light': '#fcdfd9',
        'border-disabled': '#8a949e',
        'border-gray': '#b1b8be',
        'border-gray-dark': '#58616a',
        'border-gray-darker': '#1e2124',
        'border-gray-light': '#cdd1d5',
        'border-information': '#0b78cb',
        'border-information-light': '#d3ebfd',
        'border-inverse': '#ffffff',
        'border-primary': '#2ecadc',
        'border-primary-light': '#dcf6f9',
        'border-secondary': '#eee147',
        'border-secondary-light': '#faf6c7',
        'border-success': '#228738',
        'border-success-light': '#d8eedd',
        'border-transparency': '#ffffff00',
        'border-warning': '#9e6a00',
        'border-warning-light': '#ffe0a3',

        'button-disabled-border': '#b1b8be',
        'button-disabled-fill': '#cdd1d5',
        'button-primary-fill': '#73dce7',
        'button-primary-fill-pressed': '#1b909d',
        'button-secondary-border': '#51d3e1',
        'button-secondary-fill': '#eefbfc',
        'button-secondary-fill-pressed': '#b9edf3',
        'button-tertiary-border': '#b1b8be',
        'button-tertiary-fill': '#ffffff00',
        'button-tertiary-fill-pressed': '#e6e8ea',
        'button-text-border': '#00000000',
        'button-text-fill': '#ffffff00',
        'button-text-fill-pressed': '#dcf6f9',

        'divider-gray': '#8a949e',
        'divider-gray-dark': '#6d7882',
        'divider-gray-darker': '#1e2124',
        'divider-gray-light': '#cdd1d5',

        'surface-danger-subtle': '#fdefec',
        'surface-disabled': '#cdd1d5',
        'surface-gray-subtle1': '#f4f5f6',
        'surface-gray-subtle2': '#e6e8ea',
        'surface-information-subtle': '#e7f4fe',
        'surface-inverse': '#1e2124',
        'surface-inverse-static': '#1e2124',
        'surface-primary': '#2ecadc',
        'surface-primary-light': '#eefbfc',
        'surface-primary-light-2': '#dcf6f9',
        'surface-primary-light-3': '#b9edf3',
        'surface-primary-light-4': '#96e5ed',
        'surface-primary-subtle': '#eefbfc',
        'surface-secondary-subtle': '#faf6c7',
        'surface-success-subtle': '#eaf6ec',
        'surface-warning-subtle': '#fff3db',
        'surface-white': '#ffffff',
        'surface-white-static': '#ffffff',
        'surface-white-subtle': '#ffffff',
        'surface-white-subtle-dark': '#ffffff',

        'text-basic': '#1e2124',
        'text-basic-inverse': '#e6e8ea',
        'text-bolder': '#131416',
        'text-bolder-inverse': '#ffffff',
        'text-danger': '#bd2c0f',
        'text-disabled': '#b1b8be',
        'text-disabled-on': '#6d7882',
        'text-information': '#096ab3',
        'text-inverse-static': '#ffffff',
        'text-primary': '#2ecadc',
        'text-secondary': '#e0cf15',
        'text-static': '#1e2124',
        'text-subtle': '#464c53',
        'text-subtle-inverse': '#b1b8be',
        'text-success': '#267337',
        'text-warning': '#8a5c00',

        /* ------------------------------------------------------ */
        /* --- dark mode color --- */
        /* ------------------------------------------------------ */
        'dark-action-disabled': '#33363d',
        'dark-action-primary': '#1b909d',
        'dark-action-primary-active': '#2ecadc',
        'dark-action-primary-pressed': '#0f5057',
        'dark-action-primary-selected': '#062023',
        'dark-action-white': '#000000',

        'dark-alpha-base0': '#00000000',
        'dark-alpha-base10': '#0000001a',
        'dark-alpha-base25': '#00000040',
        'dark-alpha-base50': '#00000080',
        'dark-alpha-base75': '#000000bf',
        'dark-alpha-base100': '#000000',

        'dark-alpha-inverse0': '#ffffff00',
        'dark-alpha-inverse10': '#ffffff1a',
        'dark-alpha-inverse25': '#ffffff40',
        'dark-alpha-inverse50': '#ffffff80',
        'dark-alpha-inverse75': '#ffffffbf',
        'dark-alpha-inverse100': '#ffffff',

        'dark-alpha-shadow1': '#0000001f',
        'dark-alpha-shadow2': '#00000033',
        'dark-alpha-shadow3': '#00000066',

        'dark-background-black': '#000000bf',
        'dark-background-dim': '#000000bf',
        'dark-background-gray-subtle1': '#131416',
        'dark-background-gray-subtle2': '#1e2124',
        'dark-background-inverse': '#e6e8ea',
        'dark-background-white': '#000000',

        'dark-border-danger': '#de3412',
        'dark-border-danger-light': '#390d05',
        'dark-border-disabled': '#464c53',
        'dark-border-gray': '#464c53',
        'dark-border-gray-dark': '#8a949e',
        'dark-border-gray-darker': '#e6e8ea',
        'dark-border-gray-light': '#33363d',
        'dark-border-information': '#0b78cb',
        'dark-border-information-light': '#03253f',
        'dark-border-inverse': '#000000',
        'dark-border-primary': '#2ecadc',
        'dark-border-primary-light': '#0f5057',
        'dark-border-secondary': '#e0cf15',
        'dark-border-secondary-light': '#4b4507',
        'dark-border-success': '#228738',
        'dark-border-success-light': '#122b18',
        'dark-border-transparency': '#00000000',
        'dark-border-warning': '#9e6a00',
        'dark-border-warning-light': '#2e1f00',

        'dark-button-disabled-border': '#464c53',
        'dark-button-disabled-fill': '#33363d',
        'dark-button-primary-fill': '#73dce7',
        'dark-button-primary-fill-pressed': '#1b909d',
        'dark-button-secondary-border': '#51d3e1',
        'dark-button-secondary-fill': '#062023',
        'dark-button-secondary-fill-pressed': '#15707a',
        'dark-button-tertiary-border': '#cdd1d5',
        'dark-button-tertiary-fill': '#00000000',
        'dark-button-tertiary-fill-pressed': '#33363d',
        'dark-button-text-border': '#ffffff80',
        'dark-button-text-fill': '#00000000',
        'dark-button-text-fill-pressed': '#0f5057',

        'dark-divider-gray': '#464c53',
        'dark-divider-gray-dark': '#6d7882',
        'dark-divider-gray-darker': '#e6e8ea',
        'dark-divider-gray-light': '#33363d',

        'dark-surface-danger-subtle': '#260903',
        'dark-surface-disabled': '#464c53',
        'dark-surface-gray-subtle1': '#131416',
        'dark-surface-gray-subtle2': '#1e2124',
        'dark-surface-information-subtle': '#021a2c',
        'dark-surface-inverse': '#e6e8ea',
        'dark-surface-inverse-static': '#1e2124',
        'dark-surface-primary': '#2ecadc',
        'dark-surface-primary-light': '#062023',
        'dark-surface-primary-light-2': '#0f5057',
        'dark-surface-primary-light-3': '#15707a',
        'dark-surface-primary-light-4': '#1b909d',
        'dark-surface-primary-subtle': '#062023',
        'dark-surface-secondary-subtle': '#252303',
        'dark-surface-success-subtle': '#0e2012',
        'dark-surface-warning-subtle': '#241800',
        'dark-surface-white': '#000000',
        'dark-surface-white-static': '#ffffff',
        'dark-surface-white-subtle': '#131416',
        'dark-surface-white-subtle-dark': '#1e2124',

        'dark-text-basic': '#f4f5f6',
        'dark-text-basic-inverse': '#1e2124',
        'dark-text-bolder': '#e6e8ea',
        'dark-text-bolder-inverse': '#131416',
        'dark-text-danger': '#f7afa1',
        'dark-text-disabled': '#58616a',
        'dark-text-disabled-on': '#6d7882',
        'dark-text-information': '#9ed2fa',
        'dark-text-inverse-static': '#ffffff',
        'dark-text-primary': '#b9edf3',
        'dark-text-secondary': '#f6efa2',
        'dark-text-static': '#1e2124',
        'dark-text-subtle': '#cdd1d5',
        'dark-text-subtle-inverse': '#464c53',
        'dark-text-success': '#a9dab4',
        'dark-text-warning': '#ffc95c',
      },

      borderWidth: {
        // --- light mode ---
        'border-width-static-regular': '1px',
        'border-width-variable-regular': '1px',
        'border-width-static-medium': '2px',
        'border-width-variable-medium': '2px',

        // --- dark mode ---
        // dark: dark-border-variable-regular 와 같은 식으로 사용
        'dark-border-width-static-regular': '1px',
        'dark-border-width-static-medium': '2px',
        'dark-border-width-variable-regular': '2px',
        'dark-border-width-variable-medium': '3px',
      },

      boxShadow: {
        // 그림자는 'x-offset y-offset blur-radius color' 형태로 정의함.
        // --- Light Mode---
        'shadow-blur-3': '1px',
        'shadow-y-3': '1px',
        'shadow-blur-4': '2px',
        'shadow-y-4': '2px',

        // --- Dark Mode---
        'dark-shadow-blur-3': '1px',
        'dark-shadow-blur-4': '2px',
        'dark-shadow-y-3': '2px',
        'dark-shadow-y-4': '3px',
      },

      spacing: {
        // --- primitive spacing ---
        'number-0': '0px',
        'number-1': '1px',
        'number-2': '2px',
        'number-3': '4px',
        'number-4': '6px',
        'number-5': '8px',
        'number-6': '10px',
        'number-7': '12px',
        'number-8': '16px',
        'number-9': '20px',
        'number-10': '24px',
        'number-11': '28px',
        'number-12': '32px',
        'number-13': '36px',
        'number-14': '40px',
        'number-15': '44px',
        'number-16': '48px',
        'number-17': '56px',
        'number-18': '64px',
        'number-19': '72px',
        'number-20': '80px',
        'number-21': '96px',
        'number-max': '1000px',
        // -------------------------

        // --- semantic spacing  ---
        // gap
        'g-1': '2px',
        'g-2': '4px',
        'g-3': '8px',
        'g-4': '12px',
        'g-5': '16px',
        'g-6': '20px',
        'g-7': '24px',
        'g-8': '32px',
        'g-9': '40px',
        'g-10': '48px',

        // padding
        'p-1': '2px',
        'p-2': '4px',
        'p-3': '8px',
        'p-4': '10px',
        'p-5': '12px',
        'p-6': '16px',
        'p-7': '20px',
        'p-8': '24px',
        'p-9': '32px',
        'p-10': '40px',

        // padding-card
        'p-card-xs': '16px',
        'p-card-s': '24px',
        'p-card-m': '32px',
        'p-card-l': '40px',
      },

      letterSpacing: {
        'letter-spacing-0': '0px',
        'letter-spacing-1': '1px',
      },

      lineHeight: {
        // size-height
        'h-1': '8px',
        'h-2': '16px',
        'h-3': '20px',
        'h-4': '24px',
        'h-5': '32px',
        'h-6': '40px',
        'h-7': '48px',
        'h-8': '56px',
        'h-9': '64px',
        'h-10': '72px',
        'h-11': '80px',
      },

      // --- border radius ---
      borderRadius: {
        'radius-xs': '2px',
        'radius-s': '4px',
        'radius-m1': '6px',
        'radius-m2': '8px',
        'radius-l': '10px',
        'radius-xl': '12px',
        'radius-max': '1000px',
      },

      // --- font size ---
      fontSize: {
        'body-xxs': '11px',
        'body-xs': '13px',
        'body-s': '15px',
        'body-m': '17px',
        'body-l': '19px',

        'display-xs': '24px',
        'display-s': '28px',
        'display-m': '32px',
        'display-l': '44px',

        'heading-xxxxs': '11px',
        'heading-xxxs': '13px',
        'heading-xxs': '15px',
        'heading-xs': '17px',
        'heading-s': '19px',
        'heading-m': '22px',
        'heading-l': '24px',
        'heading-xl': '28px',

        'label-xxs': '11px',
        'label-xs': '13px',
        'label-s': '15px',
        'label-m': '17px',
        'label-l': '19px',
      },

      // -- font Weight --
      fontWeight: {
        light: 300,
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },

      fontFamily: {
        sans: ['Pretendard'],
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
