/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        /* ------------------------------------------------------ */
        /* --- light mode color --- */
        /* ------------------------------------------------------ */
        'action-disabled': 'var(--color-gray-20)',
        'action-primary': 'var(--color-primary-60)',
        'action-primary-active': 'var(--color-primary-70)',
        'action-primary-pressed': 'var(--color-primary-10)',
        'action-primary-selected': 'var(--color-primary-5)',
        'action-white': 'var(--color-gray-0)',

        'alpha-base0': 'var(--color-alpha-white0)',
        'alpha-base10': 'var(--color-alpha-white10)',
        'alpha-base25': 'var(--color-alpha-white25)',
        'alpha-base50': 'var(--color-alpha-white50)',
        'alpha-base75': 'var(--color-alpha-white75)',
        'alpha-base100': 'var(--color-alpha-white100)',

        'alpha-inverse0': 'var(--color-alpha-black0)',
        'alpha-inverse10': 'var(--color-alpha-black10)',
        'alpha-inverse25': 'var(--color-alpha-black25)',
        'alpha-inverse50': 'var(--color-alpha-black50)',
        'alpha-inverse75': 'var(--color-alpha-black75)',
        'alpha-inverse100': 'var(--color-alpha-black100)',

        'alpha-shadow1': 'var(--color-alpha-shadow1)',
        'alpha-shadow2': 'var(--color-alpha-shadow2)',
        'alpha-shadow3': 'var(--color-alpha-shadow3)',

        'background-black': 'var(--color-gray-100)',
        'background-dim': 'var(--color-alpha-black75)',
        'background-gray-subtle1': 'var(--color-gray-5)',
        'background-gray-subtle2': 'var(--color-gray-10)',
        'background-inverse': 'var(--color-gray-90)',
        'background-white': 'var(--color-gray-0)',

        'border-danger': 'var(--color-danger-50)',
        'border-danger-light': 'var(--color-danger-10)',
        'border-disabled': 'var(--color-gray-40)',
        'border-gray': 'var(--color-gray-30)',
        'border-gray-dark': 'var(--color-gray-60)',
        'border-gray-darker': 'var(--color-gray-90)',
        'border-gray-light': 'var(--color-gray-20)',
        'border-information': 'var(--color-information-50)',
        'border-information-light': 'var(--color-information-10)',
        'border-inverse': 'var(--color-gray-0)',
        'border-primary': 'var(--color-primary-60)',
        'border-primary-light': 'var(--color-primary-10)',
        'border-secondary': 'var(--color-point-40)',
        'border-secondary-light': 'var(--color-point-10)',
        'border-success': 'var(--color-success-50)',
        'border-success-light': 'var(--color-success-10)',
        'border-transparency': 'var(--color-alpha-white0)',
        'border-warning': 'var(--color-warning-50)',
        'border-warning-light': 'var(--color-warning-10)',

        'button-disabled-border': 'var(--color-gray-30)',
        'button-disabled-fill': 'var(--color-gray-20)',
        'button-primary-fill': 'var(--color-primary-40)',
        'button-primary-fill-pressed': 'var(--color-primary-70)',
        'button-secondary-border': 'var(--color-primary-50)',
        'button-secondary-fill': 'var(--color-primary-5)',
        'button-secondary-fill-pressed': 'var(--color-primary-20)',
        'button-tertiary-border': 'var(--color-gray-30)',
        'button-tertiary-fill': 'var(--color-alpha-white0)',
        'button-tertiary-fill-pressed': 'var(--color-gray-10)',
        'button-text-border': 'var(--color-alpha-black0)',
        'button-text-fill': 'var(--color-alpha-white0)',
        'button-text-fill-pressed': 'var(--color-primary-10)',

        'divider-gray': 'var(--color-gray-40)',
        'divider-gray-dark': 'var(--color-gray-50)',
        'divider-gray-darker': 'var(--color-gray-90)',
        'divider-gray-light': 'var(--color-gray-20)',

        'surface-danger-subtle': 'var(--color-danger-5)',
        'surface-disabled': 'var(--color-gray-20)',
        'surface-gray-subtle1': 'var(--color-gray-5)',
        'surface-gray-subtle2': 'var(--color-gray-10)',
        'surface-information-subtle': 'var(--color-information-5)',
        'surface-inverse': 'var(--color-gray-90)',
        'surface-inverse-static': 'var(--color-gray-90)',
        'surface-primary': 'var(--color-primary-60)',
        'surface-primary-light': 'var(--color-primary-5)',
        'surface-primary-light-2': 'var(--color-primary-10)',
        'surface-primary-light-3': 'var(--color-primary-20)',
        'surface-primary-light-4': 'var(--color-primary-30)',
        'surface-primary-subtle': 'var(--color-primary-5)',
        'surface-secondary-subtle': 'var(--color-point-10)',
        'surface-success-subtle': 'var(--color-success-5)',
        'surface-warning-subtle': 'var(--color-warning-5)',
        'surface-white': 'var(--color-gray-0)',
        'surface-white-static': 'var(--color-gray-0)',
        'surface-white-subtle': 'var(--color-gray-0)',
        'surface-white-subtle-dark': 'var(--color-gray-0)',

        'text-basic': 'var(--color-gray-90)',
        'text-basic-inverse': 'var(--color-gray-10)',
        'text-bolder': 'var(--color-gray-95)',
        'text-bolder-inverse': 'var(--color-gray-0)',
        'text-danger': 'var(--color-danger-60)',
        'text-disabled': 'var(--color-gray-30)',
        'text-disabled-on': 'var(--color-gray-50)',
        'text-information': 'var(--color-information-60)',
        'text-inverse-static': 'var(--color-gray-0)',
        'text-primary': 'var(--color-primary-60)',
        'text-secondary': 'var(--color-point-50)',
        'text-static': 'var(--color-gray-90)',
        'text-subtle': 'var(--color-gray-70)',
        'text-subtle-inverse': 'var(--color-gray-30)',
        'text-success': 'var(--color-success-60)',
        'text-warning': 'var(--color-warning-60)',

        /* ------------------------------------------------------ */
        /* --- dark mode color --- */
        /* ------------------------------------------------------ */
        'dark-action-disabled': 'var(--color-gray-80)',
        'dark-action-primary': 'var(--color-primary-70)',
        'dark-action-primary-active': 'var(--color-primary-60)',
        'dark-action-primary-pressed': 'var(--color-primary-90)',
        'dark-action-primary-selected': 'var(--color-primary-95)',
        'dark-action-white': 'var(--color-gray-100)',

        'dark-alpha-base0': 'var(--color-alpha-black0)',
        'dark-alpha-base10': 'var(--color-alpha-black10)',
        'dark-alpha-base100': 'var(--color-alpha-black100)',
        'dark-alpha-base25': 'var(--color-alpha-black25)',
        'dark-alpha-base50': 'var(--color-alpha-black50)',
        'dark-alpha-base75': 'var(--color-alpha-black75)',

        'dark-alpha-inverse0': 'var(--color-alpha-white0)',
        'dark-alpha-inverse10': 'var(--color-alpha-white10)',
        'dark-alpha-inverse25': 'var(--color-alpha-white25)',
        'dark-alpha-inverse50': 'var(--color-alpha-white50)',
        'dark-alpha-inverse75': 'var(--color-alpha-white75)',
        'dark-alpha-inverse100': 'var(--color-alpha-white100)',

        'dark-alpha-shadow1': 'var(--color-dark-alpha-shadow1)',
        'dark-alpha-shadow2': 'var(--color-dark-alpha-shadow2)',
        'dark-alpha-shadow3': 'var(--color-dark-alpha-shadow3)',

        'dark-background-black': 'var(--color-alpha-black75)',
        'dark-background-dim': 'var(--color-alpha-black75)',
        'dark-background-gray-subtle1': 'var(--color-gray-95)',
        'dark-background-gray-subtle2': 'var(--color-gray-90)',
        'dark-background-inverse': 'var(--color-gray-10)',
        'dark-background-white': 'var(--color-gray-100)',

        'dark-border-danger': 'var(--color-danger-50)',
        'dark-border-danger-light': 'var(--color-danger-90)',
        'dark-border-disabled': 'var(--color-gray-70)',
        'dark-border-gray': 'var(--color-gray-70)',
        'dark-border-gray-dark': 'var(--color-gray-40)',
        'dark-border-gray-darker': 'var(--color-gray-10)',
        'dark-border-gray-light': 'var(--color-gray-80)',
        'dark-border-information': 'var(--color-information-50)',
        'dark-border-information-light': 'var(--color-information-90)',
        'dark-border-inverse': 'var(--color-gray-100)',
        'dark-border-primary': 'var(--color-primary-60)',
        'dark-border-primary-light': 'var(--color-primary-90)',
        'dark-border-secondary': 'var(--color-point-50)',
        'dark-border-secondary-light': 'var(--color-point-90)',
        'dark-border-success': 'var(--color-success-50)',
        'dark-border-success-light': 'var(--color-success-90)',
        'dark-border-transparency': 'var(--color-alpha-black0)',
        'dark-border-warning': 'var(--color-warning-50)',
        'dark-border-warning-light': 'var(--color-warning-90)',

        'dark-button-disabled-border': 'var(--color-gray-70)',
        'dark-button-disabled-fill': 'var(--color-gray-80)',
        'dark-button-primary-fill': 'var(--color-primary-40)',
        'dark-button-primary-fill-pressed': 'var(--color-primary-70)',
        'dark-button-secondary-border': 'var(--color-primary-50)',
        'dark-button-secondary-fill': 'var(--color-primary-95)',
        'dark-button-secondary-fill-pressed': 'var(--color-primary-80)',
        'dark-button-tertiary-border': 'var(--color-gray-20)',
        'dark-button-tertiary-fill': 'var(--color-alpha-black0)',
        'dark-button-tertiary-fill-pressed': 'var(--color-gray-80)',
        'dark-button-text-border': 'var(--color-alpha-white50)',
        'dark-button-text-fill': 'var(--color-alpha-black0)',
        'dark-button-text-fill-pressed': 'var(--color-primary-90)',

        'dark-divider-gray': 'var(--color-gray-70)',
        'dark-divider-gray-dark': 'var(--color-gray-50)',
        'dark-divider-gray-darker': 'var(--color-gray-10)',
        'dark-divider-gray-light': 'var(--color-gray-80)',

        'dark-surface-danger-subtle': 'var(--color-danger-95)',
        'dark-surface-disabled': 'var(--color-gray-70)',
        'dark-surface-gray-subtle1': 'var(--color-gray-95)',
        'dark-surface-gray-subtle2': 'var(--color-gray-90)',
        'dark-surface-information-subtle': 'var(--color-information-95)',
        'dark-surface-inverse': 'var(--color-gray-10)',
        'dark-surface-inverse-static': 'var(--color-gray-90)',
        'dark-surface-primary': 'var(--color-primary-60)',
        'dark-surface-primary-light': 'var(--color-primary-95)',
        'dark-surface-primary-light-2': 'var(--color-primary-90)',
        'dark-surface-primary-light-3': 'var(--color-primary-80)',
        'dark-surface-primary-light-4': 'var(--color-primary-70)',
        'dark-surface-primary-subtle': 'var(--color-primary-95)',
        'dark-surface-secondary-subtle': 'var(--color-point-95)',
        'dark-surface-success-subtle': 'var(--color-success-95)',
        'dark-surface-warning-subtle': 'var(--color-warning-95)',
        'dark-surface-white': 'var(--color-gray-100)',
        'dark-surface-white-static': 'var(--color-gray-0)',
        'dark-surface-white-subtle': 'var(--color-gray-95)',
        'dark-surface-white-subtle-dark': 'var(--color-gray-90)',

        'dark-text-basic': 'var(--color-gray-5)',
        'dark-text-basic-inverse': 'var(--color-gray-90)',
        'dark-text-bolder': 'var(--color-gray-10)',
        'dark-text-bolder-inverse': 'var(--color-gray-95)',
        'dark-text-danger': 'var(--color-danger-20)',
        'dark-text-disabled': 'var(--color-gray-60)',
        'dark-text-disabled-on': 'var(--color-gray-50)',
        'dark-text-information': 'var(--color-information-20)',
        'dark-text-inverse-static': 'var(--color-gray-0)',
        'dark-text-primary': 'var(--color-primary-20)',
        'dark-text-secondary': 'var(--color-point-20)',
        'dark-text-static': 'var(--color-gray-90)',
        'dark-text-subtle': 'var(--color-gray-20)',
        'dark-text-subtle-inverse': 'var(--color-gray-70)',
        'dark-text-success': 'var(--color-success-20)',
        'dark-text-warning': 'var(--color-warning-20)',
      },

      borderWidth: {
        // --- light mode ---
        'static-regular': 'var(--border-width-static-regular)',
        'static-medium': 'var(--border-width-static-medium)',
        'variable-regular': 'var(--border-width-variable-regular)',
        'variable-medium': 'var(--border-width-variable-medium)',

        // --- dark mode ---
        // dark: dark-border-variable-regular 와 같은 식으로 사용
        'dark-static-regular': 'var(--border-width-static-regular)', //(light 모드와 같아서 써야할지?)
        'dark-static-medium': 'var(--border-width-static-medium)', //(light 모드와 같아서 써야할지?)
        'dark-variable-regular': 'var(--border-width-variable-regular)',
        'dark-variable-medium': 'var(--border-width-variable-medium)',
      },

      boxShadow: {
        // 그림자는 'x-offset y-offset blur-radius color' 형태로 정의함.
        // --- Light Mode---
        'light-3':
          '0px var(--shadow-y-3) var(--shadow-blur-3) var(--color-alpha-shadow1)',
        'light-4':
          '0px var(--shadow-y-4) var(--shadow-blur-4) var(--color-alpha-shadow2)',

        // --- Dark Mode---
        'dark-3':
          '0px var(--shadow-dark-y-3) var(--shadow-dark-blur-3) var(--color-dark-alpha-shadow1)',
        'dark-4':
          '0px var(--shadow-y-4) var(--shadow-blur-4) var(--color-dark-alpha-shadow2)',
      },

      spacing: ({theme}) => ({
        // --- primitive spacing ---
        'number-0': '0px',
        'number-1': '1px',
        'number-2': '2px',
        'number-3': '4px',
        'number-4': '6px',
        'number-5': '8px',
        'number-6': '10px',
        'number-7': '12px',
        'number-8': '16px',
        'number-9': '20px',
        'number-10': '24px',
        'number-11': '28px',
        'number-12': '32px',
        'number-13': '36px',
        'number-14': '40px',
        'number-15': '44px',
        'number-16': '48px',
        'number-17': '56px',
        'number-18': '64px',
        'number-19': '72px',
        'number-20': '80px',
        'number-21': '96px',
        'number-max': '1000px',
        // -------------------------

        // --- semantic spacing  ---
        // gap
        'gap-1': theme('spacing.number-2'),
        'gap-2': theme('spacing.number-3'),
        'gap-3': theme('spacing.number-5'),
        'gap-4': theme('spacing.number-7'),
        'gap-5': theme('spacing.number-8'),
        'gap-6': theme('spacing.number-9'),
        'gap-7': theme('spacing.number-10'),
        'gap-8': theme('spacing.number-12'),
        'gap-9': theme('spacing.number-14'),
        'gap-10': theme('spacing.number-16'),

        // padding
        'padding-1': theme('spacing.number-2'),
        'padding-2': theme('spacing.number-3'),
        'padding-3': theme('spacing.number-5'),
        'padding-4': theme('spacing.number-6'),
        'padding-5': theme('spacing.number-7'),
        'padding-6': theme('spacing.number-8'),
        'padding-7': theme('spacing.number-9'),
        'padding-8': theme('spacing.number-10'),
        'padding-9': theme('spacing.number-12'),
        'padding-10': theme('spacing.number-14'),

        // size-height
        'size-height-1': theme('spacing.number-5'),
        'size-height-2': theme('spacing.number-8'),
        'size-height-3': theme('spacing.number-9'),
        'size-height-4': theme('spacing.number-10'),
        'size-height-5': theme('spacing.number-12'),
        'size-height-6': theme('spacing.number-14'),
        'size-height-7': theme('spacing.number-16'),
        'size-height-8': theme('spacing.number-17'),
        'size-height-9': theme('spacing.number-18'),
        'size-height-10': theme('spacing.number-19'),
        'size-height-11': theme('spacing.number-20'),

        // padding-card
        'padding-card-xsmall': theme('spacing.number-8'),
        'padding-card-small': theme('spacing.number-10'),
        'padding-card-medium': theme('spacing.number-12'),
        'padding-card-large': theme('spacing.number-14'),
      }),

      // --- border radius ---
      borderRadius: ({theme}) => ({
        'radius-xsmall': theme('spacing.number-2'),
        'radius-small': theme('spacing.number-3'),
        'radius-medium1': theme('spacing.number-4'),
        'radius-medium2': theme('spacing.number-5'),
        'radius-large': theme('spacing.number-6'),
        'radius-xlarge': theme('spacing.number-7'),
        'radius-max': theme('spacing.number-max'),
      }),

      // --- font size ---
      fontSize: {
        'font-size-body-xxsmall': ['11px', {lineHeight: 'normal'}],
        'font-size-body-xsmall': ['13px', {lineHeight: 'normal'}],
        'font-size-body-small': ['15px', {lineHeight: 'normal'}],
        'font-size-body-medium': ['17px', {lineHeight: 'normal'}],
        'font-size-body-large': ['19px', {lineHeight: 'normal'}],

        'font-size-display-xsmall': ['24px', {lineHeight: 'normal'}],
        'font-size-display-small': ['28px', {lineHeight: 'normal'}],
        'font-size-display-medium': ['32px', {lineHeight: 'normal'}],
        'font-size-display-large': ['44px', {lineHeight: 'normal'}],

        'font-size-heading-xxxxsmall-2': ['11px', {lineHeight: 'normal'}],
        'font-size-heading-xxxsmall': ['13px', {lineHeight: 'normal'}],
        'font-size-heading-xxsmall': ['15px', {lineHeight: 'normal'}],
        'font-size-heading-xsmall': ['17px', {lineHeight: 'normal'}],
        'font-size-heading-small': ['19px', {lineHeight: 'normal'}],
        'font-size-heading-medium': ['22px', {lineHeight: 'normal'}],
        'font-size-heading-large': ['24px', {lineHeight: 'normal'}],
        'font-size-heading-xlarge': ['28px', {lineHeight: 'normal'}],

        'font-size-label-xxsmall': ['11px', {lineHeight: 'normal'}],
        'font-size-label-xsmall': ['13px', {lineHeight: 'normal'}],
        'font-size-label-small': ['15px', {lineHeight: 'normal'}],
        'font-size-label-medium': ['17px', {lineHeight: 'normal'}],
        'font-size-label-large': ['19px', {lineHeight: 'normal'}],
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
