// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/kanukim97/Offnal-FE/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/kanukim97/Offnal-FE/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Shifterz', appParameters);
});
require('/Users/kanukim97/Offnal-FE/index.js');